apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpfoyer
spec:
  selector:
    matchLabels:
      app: tpfoyer
  template:
    metadata:
      labels:
        app: tpfoyer
    spec:
      containers:
      - name: db
        image: mysql:8.0.39-debian
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: db
        ports:
        - containerPort: 3306
      - name: tpfoyer
        image: xqliza/devops-foyer:latest
        ports:
        - containerPort: 8082
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5

