apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpfoyer
spec:
  selector:
    matchLabels:
      app: tpfoyer
  template:
    metadata:
      labels:
        app: tpfoyer
    spec:
      replicas: 0
      containers:
      - name: db
        image: mysql:8.0.39-debian
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        ports:
        - containerPort: 3306
      - name: tpfoyer
        image: karimzomita/devops-igl5:latest
        ports:
        - containerPort: 8082
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      initContainers:
      - name: init-wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z localhost 3306; do echo waiting for db; sleep 2; done;']
