apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpfoyer-db
spec:
  selector:
    matchLabels:
      app: tpfoyer-db
  template:
    metadata:
      labels:
        app: tpfoyer-db
    spec:
      containers:
      - name: db
        image: mysql:8.0.39-debian
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        ports:
        - containerPort: 3306
