apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpfoyer
spec:
  selector:
    matchLabels:
      app: tpfoyer
  template:
    metadata:
      labels:
        app: tpfoyer
    spec:
      containers:
      - name: tpfoyer
        image: xqliza/devops-foyer:latest
        ports:
        - containerPort: 8082