apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: prometheus-operator-grafana
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
