services:
  db:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - db_network

  api:
    image: xqliza/devops-foyer:latest
    ports:
      - "8082:8082"
    networks:
      - db_network
    depends_on:
      - db

volumes:
  mysql:

networks:
  db_network:
